config/routes.rb
RottenMangoes::Application.routes.draw do


  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resource :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

  resources :users, only: [:new, :create] 

  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update, :destroy]
    get 'sessions/impersonate/:id' => 'sessions#impersonate'
  end

    

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  include MoviesHelper

  mount_uploader :poster_image, PosterImageUploader

  has_many :reviews

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  scope :title, -> (title) do 
    where("title LIKE ?", "%#{title}%") 
  end

  scope :director, -> (director) do 
    where("director LIKE ?", "%#{director}%") 
  end

  scope :by_title_or_director, -> (phrase) do 
    where("title LIKE ? OR director LIKE ?", *(["%#{phrase}%"] * 2))
  end

  scope :range_runtime, -> (min, max) do
    where("runtime_in_minutes BETWEEN ? AND ?", min, max) 
  end

  def review_average
    reviews.size != 0 ? reviews.sum(:rating_out_of_ten)/reviews.size : 0
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :auth_admin

  def auth_admin
    unless is_admin?
      flash[:error] = "You must be logged in as admin to access this section"
      redirect_to root_path
    end
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController

  def impersonate
    flash[:notice] = "Welcome to this user account #{params[:id]}"
    session[:original_user] = session[:user_id]
    session[:user_id] = params[:id]
    redirect_to '/'
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def index
    @users = User.order(:created_at)
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_warning(@user).deliver_later
    @user.destroy
    redirect_to admin_users_path
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(
      :email, :firstname, :lastname, :password, :password_confirmation, :admin
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_admin?
    current_user && current_user.admin
  end

  def is_impersonating?
    session[:original_user] != nil
  end

  helper_method :current_user
  helper_method :is_admin?
  helper_method :is_impersonating?

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :restrict_access, except: [:show, :index]

  include MoviesHelper

  def index
    if params[:title_or_director]
      @movies = Movie.by_title_or_director(params[:title_or_director].strip).range_runtime(*range_duration(params[:runtime_in_minutes]))
    end
    @movies ||= Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new()
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image, :description
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access, :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    if is_impersonating?
      session[:user_id] = session[:original_user]
      session.delete(:original_user)
      flash[:notice] = "Welcome back"
      redirect_to :root
    else
      reset_session if current_user
      redirect_to movies_path, notice: "Adios!"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end


  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end


end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
  # return min and max values in a string
  def range_duration(statement)
    case statement
    when "Any"
      [0, 1000]
    when "Under 90 minutes"
      [0, 89]
    when "Between 90 and 120 minutes"
      [90, 120]
    when "Over 120 minutes"
      [121, 1000]
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def form_namespace
    is_admin? ? [:admin, @user] : @user
  end

end

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<%= link_to "Back to this user", admin_user_path(@user) %>

<h2>Edit this user.</h2>
<%= render 'users/form' %>

app/views/admin/users/index.html.erb
<h1>Users [Admin Page]</h1>
<table id="users">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, admin_user_path(user) %></td>
        <td><%= user.email %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<h2><%= @user.full_name %></h2>
<p>
  <%= link_to "Edit", edit_admin_user_path(@user) %>
  <%= link_to "Impersonate", "/admin/sessions/impersonate/#{@user.id}" %>
  <%= link_to "Delete", admin_user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
</p>
<h3>email: <%= @user.email %></h3>
<p>Created at: <%= @user.created_at %><p>
<p>Updated at: <%= @user.updated_at %><p>
<p>Admin? <%= @user.admin %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if current_user.admin %>
        <%= link_to "Users List", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Off Canvas Menu -->
<a class="left-off-canvas-toggle" href="#"><i class="fi-list"></i></a>

<aside class="left-off-canvas-menu">
  
  <div class="icon-bar vertical five-up">
  <a class="item">
    <i class="fi-home"></i>
    <label>Home</label>
  </a>
  <a class="item">
   <i class="fi-home"></i>
    <label>Bookmark</label>
  </a>
  <a class="item">
    <i class="fi-home"></i>
    <label>Info</label>
  </a>
  <a class="item">
    <i class="fi-home"></i>
    <label>Mail</label>
  </a>
  <a class="item">
    <i class="fi-home"></i>
    <label>Like</label>
  </a>
</div>
  
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <!-- Nav Bar -->
    <div class="small-2 column">
    </div>
    <!-- Nav Bar -->
    <div>
    <!-- Main Body -->
    <div class="small-10 column">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value) %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <!-- Main Body -->
  </div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster_image %><br>
    <%= f.file_field :poster_image %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<%= link_to image_tag(movie.poster_image.url), movie_path(movie) %>
<h2><%= link_to movie.title, movie_path(movie) %></h2>
<h2><%= movie.review_average %>/10</h2>
<h3><%= formatted_date(movie.release_date) %></h3>
<h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p><%= movie.description %></p>
<hr>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>

<%= form_tag movies_path, method: "GET" do %>
  <p>Search by</p>
  <%= label_tag(:title_or_director, "Title or director:") %>
  <%= text_field_tag :title_or_director, nil, placeholder: "Search for movie by title or director" %>

  <%= label_tag(:runtime_in_minutes, "Runtime") %>
  <%= select_tag(:runtime_in_minutes, options_for_select(["Any", "Under 90 minutes", "Between 90 and 120 minutes", "Over 120 minutes"])) %>

  <%= submit_tag("Search") %>
<% end %>

<%= render @movies %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
 <%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_image.url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)</h2>
<h3><%= @movie.release_date %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for form_namespace do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if is_admin? %>
    <div>
      <%= f.label "Set as Admin" %> <br>
      <%= f.check_box :admin %>
    </div>
  <% end %>
  <div><%= f.submit "Submit" %></div> 
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>